name: reviewdog
on: [pull_request]
jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review # Change reporter.
          path: "." # Optional.
          pattern: "*.bash" # Optional.
          exclude: "./.git/*" # Optional.
          shellcheck_flags: "-e SC1008" # shebangにimportを使用するため

